name: ServiceNow Pull Request Pipeline

on: 
  pull_request:
    branches:
      - main
     
jobs:
  build:
  # Purpose of this job is to execute ATF on current branch
    name: Run ATF on dev instance
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}

      - name: Run Tests 
        id: atf_test_dev
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName:
          browserVersion:
          osName:
          osVersion:
          testSuiteSysId: ${{ secrets.SN_ATFTESTSUITE_SYSID  }}
          testSuiteName:
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowInstallInstance: ${{ secrets.SN_DEV_INSTANCE }}
